[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Noop plugin for debugging."
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_noop"
publish = false
version = "0.12.3"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_common = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = ["concurrent"] }
swc_core = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = [
  "plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
