[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST transforms visitor for styled-jsx"
edition = "2021"
license = "Apache-2.0"
name = "styled_jsx"
version = "0.29.7"

[features]
custom_transform = ["swc_core/common_concurrent"]

[dependencies]
easy-error = "1.0.0"
tracing = "0.1.37"

swc_core = { git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440", features = [
  "common",
  "ecma_ast",
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_prefixer",
  "css_visit",
  "ecma_parser",
  "ecma_minifier",
  "ecma_utils",
  "ecma_visit",
] }

[dev-dependencies]
testing = { git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440" }
swc_core = { features = [
  "testing_transform",
], git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440" }
