[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC plugin for https://www.npmjs.com/package/babel-plugin-transform-imports"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_emotion"
publish = false
version = "0.12.5"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
serde_json = "1.0.79"
swc_common = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = ["concurrent"] }
swc_core = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = [
  "plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }
swc_emotion = {version = "0.28.0", path = "./transform"}
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
