[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>", "OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "SWC plugin for relay.dev"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_relay"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.8.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_common = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = ["concurrent"] }
swc_core = { git = "https://github.com/kwonoj/swc", rev = "56132118ef86ee30d565f6806f180e1a7cf75ce3", features = [
  "plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
